package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"time"
)

// BusinessYears is the resolver for the businessYears field.
func (r *queryResolver) BusinessYears(ctx context.Context, page *int, pageSize *int) (*BusinessYearPage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.BusinessYearRepository.List(ctx, resultPage, resultPageSize)
}

// SearchInvoices is the resolver for the searchInvoices field.
func (r *queryResolver) SearchInvoices(ctx context.Context, invoiceNumber *string, customerID *string, customerName *string, issuedFrom *time.Time, issuedTo *time.Time, page *int, pageSize *int) (*InvoicePage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.Invoices.Search(ctx, invoiceNumber, customerID, customerName, issuedFrom, issuedTo, resultPage, resultPageSize)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
