package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"bureaucracy/backend/graph/model"
	"context"
	"time"
)

// SaveCustomer is the resolver for the saveCustomer field.
func (r *mutationResolver) SaveCustomer(ctx context.Context, businessYear string, customer model.CustomerInput) (*Customer, error) {
	return r.Customers.Save(ctx, businessYear, customer)
}

// SaveInvoice is the resolver for the saveInvoice field.
func (r *mutationResolver) SaveInvoice(ctx context.Context, businessYear string, invoice model.InvoiceInput) (*Invoice, error) {
	return r.Invoices.Save(ctx, businessYear, invoice)
}

// SaveProduct is the resolver for the saveProduct field.
func (r *mutationResolver) SaveProduct(ctx context.Context, businessYear string, product model.ProductInput) (*Product, error) {
	return r.Products.Save(ctx, businessYear, product)
}

// BusinessYear is the resolver for the businessYear field.
func (r *queryResolver) BusinessYear(ctx context.Context, code string) (*BusinessYear, error) {
	return r.BusinessYearRepository.GetByCode(ctx, code)
}

// BusinessYears is the resolver for the businessYears field.
func (r *queryResolver) BusinessYears(ctx context.Context, page *int, pageSize *int) (*BusinessYearPage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.BusinessYearRepository.List(ctx, resultPage, resultPageSize)
}

// Invoice is the resolver for the invoice field.
func (r *queryResolver) Invoice(ctx context.Context, businessYear string, invoiceNumber string) (*Invoice, error) {
	return r.Invoices.GetByNumber(ctx, businessYear, invoiceNumber)
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, businessYear string, productCode string) (*Product, error) {
	return r.Products.GetByCode(ctx, businessYear, productCode)
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, businessYear string, customerID string) (*Customer, error) {
	return r.Customers.GetByID(ctx, businessYear, customerID)
}

// SearchCustomers is the resolver for the searchCustomers field.
func (r *queryResolver) SearchCustomers(ctx context.Context, businessYear string, customerID *string, customerName *string, sortBy *string, sortDirection *string, page *int, pageSize *int) (*CustomerPage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.Customers.Search(ctx, businessYear, customerID, customerName, sortBy, sortDirection, resultPage, resultPageSize)
}

// SearchInvoices is the resolver for the searchInvoices field.
func (r *queryResolver) SearchInvoices(ctx context.Context, businessYear string, invoiceNumber *string, customerID *string, customerName *string, issuedFrom *time.Time, issuedTo *time.Time, sortBy *string, sortDirection *string, page *int, pageSize *int) (*InvoicePage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.Invoices.Search(ctx, businessYear, invoiceNumber, customerID, customerName, issuedFrom, issuedTo, sortBy, sortDirection, resultPage, resultPageSize)
}

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, businessYear string, productCode *string, productName *string, sortBy *string, sortDirection *string, page *int, pageSize *int) (*ProductPage, error) {
	resultPage := 1
	if page != nil {
		resultPage = *page
	}
	resultPageSize := 20
	if pageSize != nil {
		resultPageSize = *pageSize
	}
	return r.Products.Search(ctx, businessYear, productCode, productName, sortBy, sortDirection, resultPage, resultPageSize)
}

// TaxCodes is the resolver for the taxCodes field.
func (r *queryResolver) TaxCodes(ctx context.Context, businessYear string) ([]*TaxCode, error) {
	return r.TaxCodeRepository.List(ctx, businessYear)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
