// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CustomerInput struct {
	ID                 *int     `json:"id,omitempty"`
	CustomerID         string   `json:"customerId"`
	Name               *string  `json:"name,omitempty"`
	Address            *string  `json:"address,omitempty"`
	PostalCode         *string  `json:"postalCode,omitempty"`
	City               *string  `json:"city,omitempty"`
	Country            *string  `json:"country,omitempty"`
	Contact            *string  `json:"contact,omitempty"`
	Email              *string  `json:"email,omitempty"`
	Phone              *string  `json:"phone,omitempty"`
	TaxNumber          *string  `json:"taxNumber,omitempty"`
	RegistrationNumber *string  `json:"registrationNumber,omitempty"`
	PaymentTerm        *int     `json:"paymentTerm,omitempty"`
	Discount           *float64 `json:"discount,omitempty"`
}

type InvoiceInput struct {
	ID               *int                `json:"id,omitempty"`
	InvoiceNumber    string              `json:"invoiceNumber"`
	IssueDate        *time.Time          `json:"issueDate,omitempty"`
	ServiceDate      *time.Time          `json:"serviceDate,omitempty"`
	PaymentDate      *time.Time          `json:"paymentDate,omitempty"`
	CustomerCode     *string             `json:"customerCode,omitempty"`
	CustomerName     *string             `json:"customerName,omitempty"`
	CustomerAddress  *string             `json:"customerAddress,omitempty"`
	CustomerCity     *string             `json:"customerCity,omitempty"`
	PaidAmount       *float64            `json:"paidAmount,omitempty"`
	IntroductoryText *string             `json:"introductoryText,omitempty"`
	ClosingText      *string             `json:"closingText,omitempty"`
	Items            []*InvoiceItemInput `json:"items"`
}

type InvoiceItemInput struct {
	ID          *int     `json:"id,omitempty"`
	Sequence    *int     `json:"sequence,omitempty"`
	ProductCode string   `json:"productCode"`
	TaxCode     string   `json:"taxCode"`
	Quantity    *float64 `json:"quantity,omitempty"`
	Discount    *float64 `json:"discount,omitempty"`
	NetAmount   *float64 `json:"netAmount,omitempty"`
	GrossAmount *float64 `json:"grossAmount,omitempty"`
}

type Mutation struct {
}

type ProductInput struct {
	ID          *int     `json:"id,omitempty"`
	ProductCode string   `json:"productCode"`
	Name        *string  `json:"name,omitempty"`
	Unit        *string  `json:"unit,omitempty"`
	NetPrice    *float64 `json:"netPrice,omitempty"`
	GrossPrice  *float64 `json:"grossPrice,omitempty"`
	TaxRate     *float64 `json:"taxRate,omitempty"`
	TaxCode     *string  `json:"taxCode,omitempty"`
}

type Query struct {
}
